getdelta = "getdelta\r\n"
getfinaltime_comp = "getfinaltime COMPARISON\r\n"
getsplitindex = "getsplitindex\r\n"
getcurrentrealtime = "getcurrentrealtime\r\n"
gettimerphase = "getcurrenttimerphase\r\n"
getlastsplittime = "getlastsplittime\r\n"
